services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3331:3331"
    environment:
      - DATABASE_URL=sqlite:/src/database/database.sqlite
      - NODE_ENV=production